- name: Install NGINX
  apt:
    name: nginx
    state: present

- name: Configure NGINX reverse proxy
  copy:
    dest: /etc/nginx/sites-available/yii2
    content: |
      server {
          listen 80;
          server_name 35.174.166.49;

          location / {
              proxy_pass http://localhost:8080;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
          }
      }

- name: Enable NGINX site
  file:
    src: /etc/nginx/sites-available/yii2
    dest: /etc/nginx/sites-enabled/yii2
    state: link

- name: Reload NGINX
  systemd:
    name: nginx
    state: restarted

