version: '3.8'

services:
  yii2:
    image: schmunk42/yii2-app-basic
    ports:
      - 8080:80  # Internal, NGINX will handle public routing
    networks:
      - app_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app_net:
    driver: overlay

