version: '3.8'

services:
  yii2:
    image: ghcr.io/amanhasank/pearlthoughts-demo:04c4e33b9cae0ff8f44c0822fde0643ba660833e
    ports:
      - 8080:80  # Internal, NGINX will handle public routing
    networks:
      - app_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app_net:
    driver: overlay

